services:
  db:
    image: postgres:18
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      timeout: 2s
      interval: 1s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/ephemera
      - /ephemera/node_modules
      - /ephemera/apps/server/node_modules
      - /ephemera/apps/client/node_modules
    command: sh ./docker/entrypoint.dev.sh
    ports:
      - 3000:3000
      - 5173:5173
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
