services:
  db:
    image: postgres:18
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgres_data_prod:
    name: ephemera_prod_db
