FROM node:22

WORKDIR /ephemera

RUN corepack enable

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

COPY apps/server/package.json ./apps/server/
COPY apps/client/package.json ./apps/client/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

CMD ["pnpm", "dev"]
