packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': false
  cpu-features: true
  esbuild: false
  prisma: false
  protobufjs: true
  ssh2: true
  unrs-resolver: false
injectWorkspacePackages: true
